// :::::::::::::::::::::::::::::::::::::::::::::::		TEST		 :::::::::::::::::::::::::::::::::::::::::::::::

###

GET http://localhost:8080/proyecto2/api/hola HTTP/1.1
content-type: application/json

// :::::::::::::::::::::::::::::::::::::::::::::::		LOGIN ADMIN		 :::::::::::::::::::::::::::::::::::::::::::::::

###

POST http://localhost:8080/proyecto2/api/loginadmin HTTP/1.1
content-type: application/json


{
	"user":"admin",
	"password":"201318652"
}

// :::::::::::::::::::::::::::::::::::::::::::::::		LOGIN		 :::::::::::::::::::::::::::::::::::::::::::::::

###

POST http://localhost:8080/proyecto2/api/login HTTP/1.1
content-type: application/json


{
	"user":"admin",
	"password":"201318652"
}

// :::::::::::::::::::::::::::::::::::::::::::::::		USUARIOS		 :::::::::::::::::::::::::::::::::::::::::::::::

###
POST http://localhost:8080/proyecto2/api/newuser HTTP/1.1
content-type: application/json

{
	"codigo":"bdsee22",
	"nombre":"qwsd",
	"contrasena":"e12s"
}


###
POST http://localhost:8080/proyecto2/api/loadusers HTTP/1.1
content-type: application/json

[
	{
	"codigo":"WX23",
	"nombre":"Rosita",
	"contrasena":"admin123"
	},
	{
	"codigo":"B233",
	"nombre":"Willy",
	"contrasena":"root"
	},
	{
	"codigo":"E991",
	"nombre":"Martha",
	"contrasena":"soysuper10"
	}
]

###

POST http://localhost:8080/proyecto2/api/edituser HTTP/1.1
content-type: application/json


{
	"codigo_editar":"o192",
	"codigo":"o1924",
	"nombre":"Martha Garcia",
	"contrasena":"soysuper101"
}

###

POST http://localhost:8080/proyecto2/api/deleteuser HTTP/1.1
content-type: application/json

{"codigo": "AX23"}

###

GET http://localhost:8080/proyecto2/api/getusers HTTP/1.1
content-type: application/json

###

GET http://localhost:8080/proyecto2/api/getusers64 HTTP/1.1
content-type: application/json


// :::::::::::::::::::::::::::::::::::::::::::::::		CURSOS		 :::::::::::::::::::::::::::::::::::::::::::::::

###

POST http://localhost:8080/proyecto2/api/newcurso HTTP/1.1
content-type: application/json

{
	"curso":
			{
			"codigo":"oo88",
			"nombre":"Arqui",
			"codigoCatedratico":"Auu3"
			}
}

###

POST http://localhost:8080/proyecto2/api/cargarcursos HTTP/1.1
content-type: application/json

{
	"cursos":
			[
				{
				"codigo":"oo99",
				"nombre":"Arqui",
				"codigoCatedratico":"Auu3"
				},
				{
				"codigo":"oo88",
				"nombre":"Conta",
				"codigoCatedratico":"aaaa"
				}
			]
}

###

POST http://localhost:9098/proyecto2/api/editcurso HTTP/1.1
content-type: application/json


{
	"codigo":"pp099",
	"curso":
			{
			"codigo":"pp100",
			"nombre":"EDD",
			"nombreCatedratico":"Inga. Niurka"
			}
}

###

POST http://localhost:9098/proyecto2/api/deletecurso HTTP/1.1
content-type: application/json

{"codigo": "uu88"}

###

GET http://localhost:8080/proyecto2/api/getlistacursos HTTP/1.1
content-type: application/json

###

GET http://localhost:8080/proyecto2/api/getgraficalista HTTP/1.1
content-type: application/json

// :::::::::::::::::::::::::::::::::::::::::::::::		SALONES		 :::::::::::::::::::::::::::::::::::::::::::::::

###

POST http://localhost:8080/proyecto2/api/newsalon HTTP/1.1
content-type: application/json

{
	"salon":
			{
			"csalon":"102",
			"fedificio":"T-1",
			"capacidad":"150"
			}
}

###

POST http://localhost:8080/proyecto2/api/cargarsalones HTTP/1.1
content-type: application/json

{
	"salones":
			[
				{
				"csalon":"412",
				"fedificio":"T-3",
				"capacidad":"85"
				},
				{
				"csalon":"212",
				"fedificio":"T-2",
				"capacidad":"34"
				}
			]
}

###

GET http://localhost:8080/proyecto2/api/getgraficamatriz HTTP/1.1
content-type: application/json